#version: "0.1"

services:
  app:
    # AU LIEU DE : image: bspcvtic/cvtic-lamp:latest
    # ON MET :
    build:
      context: .
      dockerfile: Dockerfile

    container_name: blog-app
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV:-dev}
